# DO NOT EDIT THIS FILE!
# This file is managed by ModuleSync.
#
# frozen_string_literal: true

require 'puppetlabs_spec_helper/module_spec_helper'

require 'rspec-puppet-facts'
include RspecPuppetFacts

RSpec.configure do |c|
  c.hiera_config = 'spec/fixtures/hiera/hiera.yaml'
end
